version: '3.8'
services:
  app:
    image: rakoryn/cosplay-shoot-manager:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Point to the local postgres service created below
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cosplay
      # Add your production environment variables here:
      # - SUPABASE_URL=your_supabase_url
      # - SUPABASE_ANON_KEY=your_supabase_anon_key
      # - SUPABASE_SERVICE_ROLE_KEY=your_supabase_service_role_key
      # - GOOGLE_OAUTH_CLIENT_ID=your_google_oauth_client_id
      # - GOOGLE_OAUTH_CLIENT_SECRET=your_google_oauth_client_secret
      # - GOOGLE_MAPS_API_KEY=your_google_maps_api_key
    volumes: []
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cosplay
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
