version: '3.8'
services:
  app:
    build: .
    image: cosplay-shoot-manager:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Point to the local postgres service created below
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cosplay
    volumes: []
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cosplay
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
