import { getGoogleDocsClient } from '../google-docs';
import type { Shoot, ShootParticipant, ShootReference } from '@shared/schema';
import { format } from 'date-fns';

interface ShootWithDetails extends Shoot {
  participants: ShootParticipant[];
  references: ShootReference[];
}

export async function createShootDocument(shoot: ShootWithDetails): Promise<{ docId: string; docUrl: string }> {
  const docs = await getGoogleDocsClient();

  const title = `${shoot.title} - Cosplay Shoot Plan`;
  
  const createResponse = await docs.documents.create({
    requestBody: {
      title,
    },
  });

  const docId = createResponse.data.documentId!;

  const requests: any[] = [];
  let currentIndex = 1;

  requests.push({
    insertText: {
      location: { index: currentIndex },
      text: `${shoot.title}\n\n`,
    },
  });
  currentIndex += shoot.title.length + 2;

  requests.push({
    updateParagraphStyle: {
      range: {
        startIndex: 1,
        endIndex: shoot.title.length + 1,
      },
      paragraphStyle: {
        namedStyleType: 'HEADING_1',
        alignment: 'CENTER',
      },
      fields: 'namedStyleType,alignment',
    },
  });

  requests.push({
    updateTextStyle: {
      range: {
        startIndex: 1,
        endIndex: shoot.title.length + 1,
      },
      textStyle: {
        bold: true,
        fontSize: {
          magnitude: 24,
          unit: 'PT',
        },
      },
      fields: 'bold,fontSize',
    },
  });

  const sections = [];

  sections.push({
    heading: 'Shoot Details',
    content: [
      `Status: ${shoot.status.charAt(0).toUpperCase() + shoot.status.slice(1)}`,
      shoot.date ? `Date: ${format(new Date(shoot.date), 'EEEE, MMMM d, yyyy')}` : null,
      shoot.location ? `Location: ${shoot.location}` : null,
    ].filter(Boolean).join('\n'),
  });

  if (shoot.description) {
    sections.push({
      heading: 'Description',
      content: shoot.description,
    });
  }

  if (shoot.participants.length > 0) {
    sections.push({
      heading: 'Participants',
      content: shoot.participants
        .map((p) => `• ${p.name} - ${p.role}${p.email ? ` (${p.email})` : ''}`)
        .join('\n'),
    });
  }

  if (shoot.references.length > 0) {
    const imageRefs = shoot.references.filter((r) => r.type === 'image');
    const instagramRefs = shoot.references.filter((r) => r.type === 'instagram');

    if (imageRefs.length > 0) {
      sections.push({
        heading: 'Reference Images',
        content: imageRefs.map((r, i) => `${i + 1}. ${r.url}`).join('\n'),
      });
    }

    if (instagramRefs.length > 0) {
      sections.push({
        heading: 'Instagram References',
        content: instagramRefs.map((r, i) => `${i + 1}. ${r.url}`).join('\n'),
      });
    }
  }

  if (shoot.instagramLinks && shoot.instagramLinks.length > 0) {
    sections.push({
      heading: 'Instagram Links',
      content: shoot.instagramLinks.map((link, i) => `${i + 1}. ${link}`).join('\n'),
    });
  }

  for (const section of sections) {
    requests.push({
      insertText: {
        location: { index: currentIndex },
        text: `${section.heading}\n`,
      },
    });
    
    const headingStart = currentIndex;
    const headingEnd = currentIndex + section.heading.length;
    currentIndex += section.heading.length + 1;

    requests.push({
      updateParagraphStyle: {
        range: {
          startIndex: headingStart,
          endIndex: headingEnd,
        },
        paragraphStyle: {
          namedStyleType: 'HEADING_2',
        },
        fields: 'namedStyleType',
      },
    });

    requests.push({
      updateTextStyle: {
        range: {
          startIndex: headingStart,
          endIndex: headingEnd,
        },
        textStyle: {
          bold: true,
          fontSize: {
            magnitude: 14,
            unit: 'PT',
          },
        },
        fields: 'bold,fontSize',
      },
    });

    requests.push({
      insertText: {
        location: { index: currentIndex },
        text: `${section.content}\n\n`,
      },
    });
    currentIndex += section.content.length + 2;
  }

  const footerText = `\n\nGenerated by CosPlay Tracker on ${format(new Date(), 'MMMM d, yyyy \'at\' h:mm a')}`;
  requests.push({
    insertText: {
      location: { index: currentIndex },
      text: footerText,
    },
  });

  requests.push({
    updateTextStyle: {
      range: {
        startIndex: currentIndex,
        endIndex: currentIndex + footerText.length,
      },
      textStyle: {
        italic: true,
        fontSize: {
          magnitude: 9,
          unit: 'PT',
        },
        foregroundColor: {
          color: {
            rgbColor: {
              red: 0.5,
              green: 0.5,
              blue: 0.5,
            },
          },
        },
      },
      fields: 'italic,fontSize,foregroundColor',
    },
  });

  await docs.documents.batchUpdate({
    documentId: docId,
    requestBody: {
      requests,
    },
  });

  const docUrl = `https://docs.google.com/document/d/${docId}/edit`;

  return { docId, docUrl };
}
